#!/usr/bin/env python3
"""
inject.py - augment a Lineage 2 SDK with native methods from PE export tables.

Workflow:

    1. From a VS Developer prompt:
           dumpbin /EXPORTS Core.dll   > Core.def
           dumpbin /EXPORTS Engine.dll > Engine.def
           dumpbin /EXPORTS NWindow.dll > NWindow.def

    2. python inject.py --def Core.def --def Engine.def --def NWindow.def \
                        --sdk path\\to\\SDK_GEN\\L2\\SDK

For every public, non-ctor/dtor/operator C++ export the tool emits an inline
GetProcAddress-backed trampoline inside the matching class block in the
generated SDK headers. Existing autogenerated members are not modified; new
entries appear in a clearly delimited "Native exports" block right before the
closing brace of the class.

Requirements: llvm-undname (LLVM) OR undname.exe (Visual Studio). The script
auto-detects whichever is on PATH.
"""

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path


# --- .def parser -------------------------------------------------------------

_DEF_LINE = re.compile(
    r"^\s*(?P<ord>\d+)\s+"
    r"(?P<hint>[0-9A-Fa-f]+)\s+"
    r"(?P<rva>[0-9A-Fa-f]+)\s+"
    r"(?P<name>\S+)\s*$"
)


def _read_text(path: Path) -> str:
    """dumpbin writes the .def in UTF-16 LE; tolerate UTF-8 too."""
    raw = path.read_bytes()
    if raw.startswith(b"\xff\xfe") or b"\x00" in raw[:64]:
        return raw.decode("utf-16-le", errors="replace")
    return raw.decode("utf-8", errors="replace")


def parse_def(path: Path):
    """Return [{ordinal, hint, rva, mangled}] for every C++-mangled export."""
    text = _read_text(path)
    exports = []
    for line in text.splitlines():
        m = _DEF_LINE.match(line)
        if not m:
            continue
        name = m.group("name")
        if not name.startswith("?"):
            # Plain C exports (StaticInit, etc.) - skip; we only trampoline class methods.
            continue
        exports.append({
            "ordinal": int(m.group("ord")),
            "hint": int(m.group("hint"), 16),
            "rva": int(m.group("rva"), 16),
            "mangled": name,
        })
    return exports


# --- demangling --------------------------------------------------------------

def _find_demangler():
    for tool in ("llvm-undname", "undname.exe", "undname"):
        try:
            subprocess.run([tool, "--help"], capture_output=True, check=False, timeout=4)
            return tool
        except (FileNotFoundError, subprocess.TimeoutExpired):
            continue
    return None


def demangle_batch(mangled_names):
    """Pipe every mangled name through the demangler and return parallel list."""
    tool = _find_demangler()
    if tool is None:
        sys.exit("error: install LLVM (llvm-undname) or run from a VS Developer prompt (undname.exe).")

    stdin = "\n".join(mangled_names) + "\n"
    proc = subprocess.run([tool], input=stdin, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        sys.exit(f"error: {tool} exited with code {proc.returncode}\n{proc.stderr}")

    # llvm-undname format: "<mangled>\n<demangled>\n\n" per input.
    # undname.exe format:  "<index>:- <mangled>\nis :- <demangled>\n\n" - we
    #                       strip the labels so both look the same.
    lines = [l for l in proc.stdout.splitlines() if l.strip()]
    results = []
    i = 0
    for name in mangled_names:
        if i >= len(lines):
            results.append("")
            continue
        # Skip the echoed mangled (llvm) or "N:- mangled" (undname).
        if name in lines[i]:
            i += 1
        if i >= len(lines):
            results.append("")
            continue
        demangled = lines[i]
        i += 1
        # undname prepends "is :- ".
        demangled = re.sub(r"^is\s*:-\s*", "", demangled)
        results.append(demangled.strip())
    return results


# --- signature parser --------------------------------------------------------

_SIG = re.compile(
    r"^(?P<access>public|private|protected):\s*"
    r"(?P<modifier>static\s+|virtual\s+)?"
    r"(?P<retn>.*?)\s+"
    r"(?P<conv>__cdecl|__thiscall|__stdcall|__fastcall)\s+"
    r"(?P<cls>[A-Za-z_][\w:]*)::(?P<method>[~`A-Za-z_][\w<>~`'? ]*?)\s*"
    r"\((?P<params>.*)\)\s*"
    r"(?P<cv>const\s*)?$"
)


def parse_signature(demangled):
    m = _SIG.match(demangled)
    if not m:
        return None
    mod = (m.group("modifier") or "").strip()
    return {
        "access": m.group("access"),
        "static": mod == "static",
        "virtual": mod == "virtual",
        "return_type": m.group("retn").strip(),
        "calling_conv": m.group("conv"),
        "class": m.group("cls").strip(),
        "method": m.group("method").strip(),
        "params": _split_params(m.group("params")),
        "const": bool(m.group("cv")),
    }


def _split_params(s):
    s = s.strip()
    if not s or s == "void":
        return []
    parts = []
    depth = 0
    cur = []
    for ch in s:
        if ch in "<(":
            depth += 1
            cur.append(ch)
        elif ch in ">)":
            depth -= 1
            cur.append(ch)
        elif ch == "," and depth == 0:
            parts.append("".join(cur).strip())
            cur = []
        else:
            cur.append(ch)
    if cur:
        parts.append("".join(cur).strip())
    return parts


# --- C++ generation ----------------------------------------------------------

def _normalize_type(t):
    """Tidy MSVC demangler whitespace into a compact, idiomatic form."""
    t = re.sub(r"\bclass\s+", "class ", t)
    t = re.sub(r"\bstruct\s+", "struct ", t)
    # "wchar_t const *"  ->  "const wchar_t*"
    t = re.sub(r"(\b\w[\w:]*)\s+const\b", r"const \1", t)
    t = re.sub(r"\s*\*", "*", t)
    t = re.sub(r"\s*&", "&", t)
    t = re.sub(r"\s+", " ", t).strip()
    return t


def _skip(sig):
    if sig["access"] != "public":
        return True
    cls = sig["class"].rsplit("::", 1)[-1]
    if sig["method"] == cls or sig["method"] == "~" + cls:
        return True
    if sig["method"].startswith("operator") or sig["method"].startswith("?"):
        return True
    return False


def emit_trampoline(sig, mangled, dll, rva):
    """Render an inline GetProcAddress-backed wrapper for one export."""
    retn = _normalize_type(sig["return_type"])
    params = [_normalize_type(p) for p in sig["params"]]
    p_decl = ", ".join(f"{p} P{i}" for i, p in enumerate(params))
    p_call = ", ".join(f"P{i}" for i in range(len(params)))

    if sig["static"]:
        fn_t_params = ", ".join(params)
        fn_t = f"{retn}(__cdecl*)({fn_t_params})"
        call_args = p_call
        prefix = "inline static "
    else:
        thiscall_params = ["void*"] + params
        fn_t = f"{retn}(__thiscall*)({', '.join(thiscall_params)})"
        call_args = "this" if not params else "this, " + p_call
        prefix = "inline "

    cv = " const" if sig["const"] else ""
    ret_kw = "return " if retn != "void" else ""

    return (
        f"\t// {mangled} @ 0x{rva:08X}\n"
        f"\t{prefix}{retn} Native_{sig['method']}({p_decl}){cv}\n"
        f"\t{{\n"
        f"\t\tusing Fn = {fn_t};\n"
        f"\t\tstatic auto fn = reinterpret_cast<Fn>(GetProcAddress(GetModuleHandleW(L\"{dll}\"), \"{mangled}\"));\n"
        f"\t\t{ret_kw}fn({call_args});\n"
        f"\t}}"
    )


# --- SDK header patcher ------------------------------------------------------

_CLASS_HDR = re.compile(
    r"^(?P<head>(?:class|struct)\s+(?P<name>\w+)(?:\s*:\s*[^{\n]+)?)\s*\n\{",
    re.MULTILINE,
)

_INJECT_BEGIN = "// === BEGIN auto-injected native exports ==="
_INJECT_END = "// === END auto-injected native exports ==="


def _find_class_blocks(text):
    """Yield (class_name, header_start, body_start, body_end_after_close) tuples.

    body_end_after_close is the offset of the character right after the `};` that
    closes the class - i.e. the place we want to splice trampolines just before.
    """
    for m in _CLASS_HDR.finditer(text):
        body_start = m.end()  # position right after `{`
        depth = 1
        i = body_start
        while i < len(text) and depth > 0:
            ch = text[i]
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    # `};` follows on the same character (close brace), the next
                    # is `;`. Snap to the `};` location.
                    yield m.group("name"), m.start(), body_start, i
                    break
            i += 1


def _strip_previous_injection(body):
    """Remove a previously-injected block so reruns are idempotent."""
    return re.sub(
        rf"\n[ \t]*{re.escape(_INJECT_BEGIN)}.*?{re.escape(_INJECT_END)}\n",
        "\n",
        body,
        flags=re.DOTALL,
    )


def patch_file(path, exports_by_class, report):
    text = path.read_text(encoding="utf-8", errors="replace")
    original = text

    # Strip stale injections first so the script is idempotent.
    text = _strip_previous_injection(text)

    # Find class blocks in reverse so earlier offsets stay valid as we mutate.
    blocks = list(_find_class_blocks(text))
    blocks.sort(key=lambda b: b[3], reverse=True)

    for name, _hdr_start, _body_start, close_idx in blocks:
        exports = exports_by_class.get(name)
        if not exports:
            continue
        report.setdefault(name, {"file": str(path), "added": []})
        block_lines = [
            "",
            f"\t{_INJECT_BEGIN}",
            f"\t//   Source: {', '.join(sorted({e['dll'] for e in exports}))}",
            f"\t//   Count : {len(exports)}",
        ]
        for sig in exports:
            block_lines.append(emit_trampoline(sig, sig["mangled"], sig["dll"], sig["rva"]))
            report[name]["added"].append(sig["method"])
        block_lines.append(f"\t{_INJECT_END}")
        block_lines.append("")  # blank line before `};`

        insertion = "\n".join(block_lines)
        text = text[:close_idx] + insertion + text[close_idx:]

    if text != original:
        path.write_text(text, encoding="utf-8")
        return True
    return False


# --- main --------------------------------------------------------------------

def _dll_name_from_def(path: Path) -> str:
    """Treat the .def filename stem (after any leading hash prefix) as the DLL."""
    stem = path.stem
    if "-" in stem:
        stem = stem.split("-", 1)[1]
    return stem + ".dll"


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--def", dest="defs", action="append", required=True,
                    help="Path to a dumpbin /EXPORTS .def file (repeatable).")
    ap.add_argument("--sdk", required=True,
                    help="Generated SDK directory (the folder with *_classes.hpp).")
    ap.add_argument("--ext", default="hpp", help="Header extension to scan (default: hpp).")
    ap.add_argument("--dry-run", action="store_true",
                    help="Report what would change without writing any file.")
    args = ap.parse_args()

    exports_by_class = {}
    total_seen = 0
    total_kept = 0
    for d in args.defs:
        p = Path(d)
        dll = _dll_name_from_def(p)
        print(f"[+] reading {p}  ->  module {dll}")
        exps = parse_def(p)
        total_seen += len(exps)
        if not exps:
            print(f"    (no C++ exports found)")
            continue
        names = [e["mangled"] for e in exps]
        demangled = demangle_batch(names)
        kept = 0
        for e, dm in zip(exps, demangled):
            sig = parse_signature(dm)
            if sig is None or _skip(sig):
                continue
            sig["dll"] = dll
            sig["mangled"] = e["mangled"]
            sig["rva"] = e["rva"]
            cls = sig["class"].rsplit("::", 1)[-1]
            exports_by_class.setdefault(cls, []).append(sig)
            kept += 1
        total_kept += kept
        print(f"    {len(exps)} mangled / {kept} trampolines")

    print(f"\n[+] {total_seen} exports scanned, {total_kept} trampolines collected,"
          f" {len(exports_by_class)} distinct classes")

    sdk = Path(args.sdk)
    if not sdk.is_dir():
        sys.exit(f"--sdk not a directory: {sdk}")

    report = {}
    changed_files = 0
    for path in sorted(sdk.rglob(f"*.{args.ext}")):
        if args.dry_run:
            text = path.read_text(encoding="utf-8", errors="replace")
            stripped = _strip_previous_injection(text)
            blocks = list(_find_class_blocks(stripped))
            hits = [b for b in blocks if b[0] in exports_by_class]
            if hits:
                print(f"[dry] {path.relative_to(sdk)}:")
                for name, *_ in hits:
                    print(f"        + {name}   ({len(exports_by_class[name])} methods)")
        else:
            if patch_file(path, exports_by_class, report):
                changed_files += 1
                print(f"[+] patched {path.relative_to(sdk)}")

    if not args.dry_run:
        print(f"\n[done] {changed_files} file(s) updated, "
              f"{sum(len(v['added']) for v in report.values())} method(s) injected across "
              f"{len(report)} class(es).")


if __name__ == "__main__":
    main()
